---
kind: pipeline
type: kubernetes
name: devhub-frontend

trigger:
  branch:
    # TODO replace with staging
    - DEVHUB-819

# List of pipeline steps.
steps:
  - name: publish
    image: plugins/ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: 795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      values_files: [ "environments/prod.yaml" ]
    when:
      event:
        - push

  - name: deploy-staging
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.7.3
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: devrel
      release: devhub-ui
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME},ingress.enabled=true,ingress.hosts[0]=devhub-ui.devrel.staging.corp.mongodb.com
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
      values_files: [ "environments/staging.yaml" ]
    when:
      event:
        - push

---
kind: pipeline
type: kubernetes
name: deploy

trigger:
  branch:
    # TODO replace with staging
    - DEVHUB-819-prod
steps:
  - name: deploy-prod
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.7.3
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: devrel
      release: devhub-ui
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME},ingress.enabled=true,ingress.hosts[0]=devhub-ui.devrel.prod.corp.mongodb.com
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
      values_files: ["environments/prod.yaml"]
    when:
      event:
        - push